name: Build VPK
on:
  push:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    container: vitasdk/vitasdk:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cmake -S . -B build
          cmake --build build
      - uses: actions/upload-artifact@v4
        with:
          name: Saity-V1-Installer
          path: build/*.vpk
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0
          files: build/*.vpk
